---
# Run jupyter notebook for data science

- name: Copy python/r script and data set to server
  copy:
    src: "{{ item }}"
    dest: "{{ script_file_path }}"
  with_fileglob:
        - "data/datascience/*.*"

# Env 설정 : container image 이름 (하나의 서버에 여러개의 container 구동 가능한 상황)
- name: Find container id of launchbag-datascience
  shell: docker ps | grep {{ container_name}} | awk '{ print $1}'
  register: container_id

- name: Print Jupyter notebook logs
  debug:
    var: container_id

- name: Wait for the jupyter notebook server to start
  command: docker logs {{ container_id.stdout }}
  register: jupyter_logs
  until: jupyter_logs.stdout.find("The Jupyter Notebook is running") != -1
  retries: 30
  delay: 10

- name: Print Jupyter notebook logs
  debug:
    var: jupyter_logs

- name: Set jupyter notebok token
  set_fact:
    token_str: "{{ jupyter_logs.stdout | regex_search('[_a-zA-Z0-9-]{48}')}}"

- name: Print extracted token
  debug:
    var: token_str

# Env설정 : 저장 path
- name: Save jupyter-notebook token to file (token.txt)
  lineinfile:
    path: "{{ token_file_path }}"
    line: "http://{{ token_str  }}"
    create: yes

- name: Install python package for analysis
  shell: docker exec -d {{ container_id.stdout }} pip install compositions

- name: Get the datascience service-id
  action: uri
      method=GET
      status_code=200
      url="http://{{ rancher_server }}:{{ rancher_port }}/v2-beta/services" return_content=yes
  register: service_id

- name: Print extracted token
  debug:
    var: service_id
