---
# Run elk-stack for data science
- name: Install the curl command for rancher api
  yum:
   name: curl
   state: present

- name: Save launchbag-datascience json contents to variable
  set_fact:
    json_contenst: "{{ lookup('template', 'templates/launchbag-elk.json.j2') }}"
#    json_contenst: "{{ lookup('file','templates/launchbag-datascience.json') }}"

- name : Run launchbag services using curl command (uri 모듈로 변경 필요)
  shell: "{{ json_contenst }}"
  register: out_shell

- name : set shell result to json format
  set_fact:
    elk_result: "{{ out_shell.stdout|from_json }}"

# - name: Print output of curl command
#   debug:
#     msg: "{{ elk_result }}"

# - name: Print output of curl command
#   debug:
#     msg: "{{ elk_result['actions']['activateservices'] }}"

- name : set stack id
  set_fact:
    elk_activate: "{{ elk_result['actions']['activateservices'] }}"

- name : Activate elk service
  shell: >
   curl -u "BAF2FFEB1637F9A4F735:pitwPkiXLDYQnQrJWDo618q2REVnxVuNZ2AM2Bq2"
   -X POST
   -H 'Accept: application/json'
   -H 'Content-Type: application/json'
   -d '{}'
   "{{ elk_activate }}"

- name: Check elasticsearch server
  action: uri
      method=GET
      status_code=200
      url="http://{{ rancher_server}}:9200" return_content=yes
  register: elasticsearch_result
  until: elasticsearch_result.status == 200
  retries: 10
  delay: 10

- name: Print output of curl command
  debug:
    msg: "{{ elasticsearch_result }}"


- name: Copy python/r script and data set to server
  copy:
   src: "{{ item }}"
   dest: "{{ elk_file_path }}"
   force: no
  with_fileglob:
       - "data/elk/*.*"


# - name : Create elasticsearch index (ba_realtime)
#   shell: >
#     curl
#     -X PUT
#     -H 'Content-Type: application/json'
#     -d '{}'
#     '{{ rancher_server }}:9200/ba_realtime3?pretty'


- name: Run Data generator
  shell: python ./data_generator.py </dev/null >/dev/null 2>&1
  async: 600
  poll: 0

- name: Create kibana index pattern (ba_realtime)
  shell: >
    curl
    -X PUT
    -H 'Content-Type: application/json'
    -d '{"title" : "ba_realtime", "timeFieldName": "@timestamp"}}'
    '{{ rancher_server }}:9200//.kibana/index-pattern/ba_realtime'
